# .github/workflows/deploy.yml
name: CI/CD Pipeline for Adaptive Data Fusion

# Controls when the workflow will run
on:
  # Triggers the workflow on push events to main branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Environment variables
env:
  NODE_VERSION: 18.x

# Jobs in the workflow
jobs:
  # Build and test job
  build-and-test:
    name: Build, Test, and Deploy
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Run linter
      - name: Run Linter
        run: npm run lint

      # Run tests
      - name: Run Tests
        run: npm test

      # Build the project
      - name: Build Project
        run: npm run build
        
      # Upload build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          retention-days: 5

